#
# Load the device configuration for Mitsubishi CN105 Controller.  This is a direct
# replacement for Mitsubishi Kumo Cloud Wifi Controller
#
packages:
  - !include common/mitsubishi_cn105_config.yaml
  - !include common/mitsubishi_cn105_wifi_dynamic.yaml
  - !include common/mitsubishi_cn105_remote_temp_dual.yaml
  - !include common/mitsubishi_cn105_device_base.yaml

# The packages have requirements regarding substitutions that need to be answered.
substitutions:
  name: midu-climate-master-bedroom
  friendly_name: Mitsubishi Master Bedroom
  rts_primary_sensor: sensor.z2m_master_bedroom_temp_humidity_temperature
  rts_backup_sensor: sensor.master_bedroom_thermostat_electric_air_temperature
  
  # The rts_average_value controls if the primary/backup are averaged or not.  The default
  # is to average them unless you set that value to 0 (false).  If set to 1 then the 
  # primary is used unless it become unavailable in which case the backup is used.  If
  # neither is available the split mini will ultimately revert back to its internal sensor.
  #   rts_average_value: 0
  
  # Wifi Setup
  wifi_ssid: !secret wifi_iot_ssid
  wifi_password: !secret wifi_iot_password

  # Wifi Access Point Fallback
  wifi_ap_fallback_ssid: !secret fallback_ssid_midu_master_bedroom
  wifi_ap_fallback_password: !secret fallback_password_midu_master_bedroom

  # Various passwords
  api_key: !secret api_key_midu_master_bedroom
  ota_key: !secret ota_key_midu_master_bedroom

  # Setup web server authentication
  # To disable the web server add the following after the substitution section:
  #     web_server: !remove
  ws_username: !secret web_server_username
  ws_password: !secret web_server_password
  #

# Disable the web server component
web_server: !remove
