#
# This package contains the Wifi configuration setup using DHCP to obtain the IP address.
# This package requires the following substitutions to be defined:
#
#  - Wifi Setup
#        wifi_ssid           -> SSID of wifi network to use
#        wifi_password       -> Password for wifi network 
#        wifi_domain         -> Default domain name to use, allows non ".local" domains
#
#  - Wifi Access Point Fallback
#        wifi_ap_fallback_ssid      -> Fallback Access Point SSID
#        wifi_ap_fallback_password. -> Fallbcak Access Point Password

substitutions:
    wifi_domain: .local

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  domain: ${wifi_domain}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${wifi_ap_fallback_ssid}
    password: ${wifi_ap_fallback_password}

